"""The portfolio's content, baked in at deploy time.

`data/site.json` is generated by `scripts/sync_site_content.mjs` from
portfolio-v2. Re-run that script when the portfolio's projects or writing
change, or this goes stale silently.

Read once and cached, not per request. On serverless the module survives
between invocations, so this costs one file read per cold start.
"""

import json
from functools import lru_cache
from pathlib import Path

_SITE_JSON = Path(__file__).parent / "data" / "site.json"


@lru_cache
def content() -> dict:
    return json.loads(_SITE_JSON.read_text(encoding="utf-8"))


def projects() -> list[dict]:
    return content()["projects"]


def pages() -> list[dict]:
    return content()["pages"]


def site() -> dict:
    return content()["site"]


def profile() -> dict:
    """Public background facts copied from the portfolio at deploy time."""
    data = content()
    return {
        "site": data["site"],
        "experience": data["experience"],
        "education": data["education"],
        "toolbox": data["toolbox"],
    }


def current_page(path: str | None) -> dict | None:
    """Return trusted page context only for a route that actually exists."""
    if not path:
        return None
    normalized = "/" + path.strip().strip("/") if path.strip() != "/" else "/"
    if normalized == "/":
        return {
            "route": "/",
            "title": "home",
            "description": "Ammar's portfolio home page with selected work and recent writing.",
        }
    return next((page for page in pages() if page["route"] == normalized), None)
